// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJD-jCuf6PHusdGUmPaTd8Mwi2uXow0TY',
    appId: '1:120685828049:web:a52bf211054bc9cf8db2f0',
    messagingSenderId: '120685828049',
    projectId: 'chat-app-b75fc',
    authDomain: 'chat-app-b75fc.firebaseapp.com',
    storageBucket: 'chat-app-b75fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANFDNEb4Xs6KIq9ADw2eEa7yg4XutBsEU',
    appId: '1:120685828049:android:6801b2b3cef18f9d8db2f0',
    messagingSenderId: '120685828049',
    projectId: 'chat-app-b75fc',
    storageBucket: 'chat-app-b75fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV4q-BPa8YHhkGovHKFuuLAcpWJRpgSRE',
    appId: '1:120685828049:ios:adf31a19557d35968db2f0',
    messagingSenderId: '120685828049',
    projectId: 'chat-app-b75fc',
    storageBucket: 'chat-app-b75fc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV4q-BPa8YHhkGovHKFuuLAcpWJRpgSRE',
    appId: '1:120685828049:ios:adf31a19557d35968db2f0',
    messagingSenderId: '120685828049',
    projectId: 'chat-app-b75fc',
    storageBucket: 'chat-app-b75fc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJD-jCuf6PHusdGUmPaTd8Mwi2uXow0TY',
    appId: '1:120685828049:web:a73b8e73537993118db2f0',
    messagingSenderId: '120685828049',
    projectId: 'chat-app-b75fc',
    authDomain: 'chat-app-b75fc.firebaseapp.com',
    storageBucket: 'chat-app-b75fc.appspot.com',
  );
}
